### ISSUE TITLE
Error: Metamask Error 

### ISSUE THREAD

**Issue by Naman-1234** [Ohh-404-BrainNotFound/Cryptolx-Frontend#13]
Till Metamask does not get connected and the page refreshed, Page is getting the following error:
![Screenshot (1360)](https://user-images.githubusercontent.com/63748249/140599174-05803d0c-3b1f-4695-93a6-94f214deec80.png)

**Comment by nlok5923** [comment]
ig one of mine recent pushes fixed it.
